languageCode = "en"
languageName = "English"
weight = 1

title = "Zachary Henard"
# logo = "/images/zachary_twitter_avatar.jpg"
copyright = "All content licensed [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) 💜"

[params]
  isoCode = "en"
  displayName = "EN"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Cybersecurity Student & DIY Tech Fanatic :closed_lock_with_key:"

[author]
  name = "Zachary Henard"
  image = "zachary_avatar.png"
  headline = "Cybersecurity Student & DIY Tech Fanatic :closed_lock_with_key:"
  bio = "I enjoy exploring all aspects of IT and sharing what I learn with others."
  links = [
    { email = "mailto:zachary@henard.tech" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
   { github = "https://github.com/zdhenard42" },
  #   { gitlab = "https://gitlab.com/" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
   { linkedin = "https://www.linkedin.com/in/zhenard/" },
  #   { mastodon = "https://social.lol" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
  ]
