languageCode = "en"
languageName = "English"
weight = 1

title = "Zachary Henard"
# logo = "/images/zachary_twitter_avatar.jpg"
copyright = "All content licensed [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) 💜"

[params]
  isoCode = "en"
  displayName = "EN"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Passionate Computer Scientist & DIY Tech Fanatic :closed_lock_with_key:"
  image = "zachary_avatar.png"
  headline = "Passionate Computer Scientist & DIY Tech Fanatic :closed_lock_with_key:"
  bio = "I enjoy exploring all aspects of IT and sharing what I learn with others."

